"""H3 Harness SDK for Python — build agent harnesses compatible with Hermes Core."""

from ._version import __version__
from .harness import BaseHarness, create_router
from .middleware import add_middleware
from .protocol import (
    CancelReason,
    CancelRequest,
    Decision,
    DecisionType,
    Delegate,
    End,
    EndReason,
    ErrorCode,
    ErrorResponse,
    HealthResponse,
    HealthStatus,
    LLMCall,
    ProcessRequest,
    ResultPayload,
    ResultRequest,
    ResultType,
    SessionResponse,
    SessionStatus,
    TextResponse,
    ToolCall,
    Wait,
)

__all__ = [
    "__version__",
    "BaseHarness",
    "create_router",
    "add_middleware",
    "CancelReason",
    "CancelRequest",
    "Decision",
    "DecisionType",
    "Delegate",
    "End",
    "EndReason",
    "ErrorCode",
    "ErrorResponse",
    "HealthResponse",
    "HealthStatus",
    "LLMCall",
    "ProcessRequest",
    "ResultPayload",
    "ResultRequest",
    "ResultType",
    "SessionResponse",
    "SessionStatus",
    "TextResponse",
    "ToolCall",
    "Wait",
]
